name: Build Pi-Gen Image

on:
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  build-image:
    runs-on: ubuntu-22.04 # Explicitly specify the Ubuntu version

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git \
            coreutils \
            quilt \
            parted \
            qemu-user-static \
            debootstrap \
            zerofree \
            zip \
            dosfstools \
            libarchive-tools \
            libcap2-bin \
            rsync \
            grep \
            xz-utils \
            file \
            curl \
            cpio \
            python3 \
            python3-pip \
            jq \
            binfmt-support \
            systemd-container \
            arch-test

      - name: Grant Execution Permissions
        run: chmod +x build.sh

      - name: Run Build Script as Root
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}
        run: |
          sudo ./build.sh

      - name: Archive and Upload Build Artifacts
        if: always()
        uses: actions/upload-artifact@v4 # Updated to v4
        with:
          name: pi-gen-image
          path: deploy/

